"""Initial schema with signals trends and users

Revision ID: 7094d093554c
Revises: 
Create Date: 2025-10-10 13:11:49.968568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7094d093554c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('identifier', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content_preview', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('signal_metadata', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('content_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_collected', 'raw_signals', ['category', 'collected_at'], unique=False)
    op.create_index('idx_platform_category_created', 'raw_signals', ['platform', 'category', 'content_created_at'], unique=False)
    op.create_index(op.f('ix_raw_signals_category'), 'raw_signals', ['category'], unique=False)
    op.create_index(op.f('ix_raw_signals_collected_at'), 'raw_signals', ['collected_at'], unique=False)
    op.create_index(op.f('ix_raw_signals_content_created_at'), 'raw_signals', ['content_created_at'], unique=False)
    op.create_index(op.f('ix_raw_signals_id'), 'raw_signals', ['id'], unique=False)
    op.create_index(op.f('ix_raw_signals_platform'), 'raw_signals', ['platform'], unique=False)
    op.create_table('trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('velocity_score', sa.Float(), nullable=True),
    sa.Column('saturation_level', sa.String(length=20), nullable=True),
    sa.Column('saturation_score', sa.Float(), nullable=True),
    sa.Column('novelty_score', sa.Float(), nullable=True),
    sa.Column('seer_score', sa.Float(), nullable=True),
    sa.Column('predicted_peak_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('first_detected', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=True),
    sa.Column('source_platforms', sa.JSON(), nullable=True),
    sa.Column('chart_data', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_seer_score', 'trends', ['category', 'seer_score'], unique=False)
    op.create_index('idx_status_updated', 'trends', ['status', 'last_updated'], unique=False)
    op.create_index(op.f('ix_trends_category'), 'trends', ['category'], unique=False)
    op.create_index(op.f('ix_trends_id'), 'trends', ['id'], unique=False)
    op.create_index(op.f('ix_trends_name'), 'trends', ['name'], unique=False)
    op.create_index(op.f('ix_trends_seer_score'), 'trends', ['seer_score'], unique=False)
    op.create_index(op.f('ix_trends_slug'), 'trends', ['slug'], unique=True)
    op.create_index(op.f('ix_trends_status'), 'trends', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('persona', sa.String(length=100), nullable=True),
    sa.Column('selected_categories', sa.JSON(), nullable=True),
    sa.Column('platform_preferences', sa.JSON(), nullable=True),
    sa.Column('goal_emphasis', sa.JSON(), nullable=True),
    sa.Column('plan_tier', sa.String(length=20), nullable=True),
    sa.Column('plan_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_renewal_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weekly_uploads_used', sa.Integer(), nullable=True),
    sa.Column('weekly_uploads_reset_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('theme_accent', sa.String(length=50), nullable=True),
    sa.Column('theme_background', sa.String(length=50), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('trending_alerts', sa.Boolean(), nullable=True),
    sa.Column('watchlist_updates', sa.Boolean(), nullable=True),
    sa.Column('weekly_digest', sa.Boolean(), nullable=True),
    sa.Column('analytics_sharing', sa.Boolean(), nullable=True),
    sa.Column('public_profile', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_time', sa.String(length=10), nullable=True),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_date', 'calendar_events', ['user_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_calendar_events_event_date'), 'calendar_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_events_trend_id'), 'calendar_events', ['trend_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_table('trend_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['raw_signals.id'], ),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trend_relevance', 'trend_evidence', ['trend_id', 'relevance_score'], unique=False)
    op.create_index(op.f('ix_trend_evidence_id'), 'trend_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_trend_evidence_signal_id'), 'trend_evidence', ['signal_id'], unique=False)
    op.create_index(op.f('ix_trend_evidence_trend_id'), 'trend_evidence', ['trend_id'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('custom_tags', sa.JSON(), nullable=True),
    sa.Column('alert_on_heating', sa.Boolean(), nullable=True),
    sa.Column('alert_on_cooling', sa.Boolean(), nullable=True),
    sa.Column('alert_threshold', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_snapshot', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_priority', 'watchlist', ['user_id', 'priority'], unique=False)
    op.create_index('idx_user_trend', 'watchlist', ['user_id', 'trend_id'], unique=True)
    op.create_index(op.f('ix_watchlist_id'), 'watchlist', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_trend_id'), 'watchlist', ['trend_id'], unique=False)
    op.create_index(op.f('ix_watchlist_user_id'), 'watchlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_user_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_trend_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_id'), table_name='watchlist')
    op.drop_index('idx_user_trend', table_name='watchlist')
    op.drop_index('idx_user_priority', table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_trend_evidence_trend_id'), table_name='trend_evidence')
    op.drop_index(op.f('ix_trend_evidence_signal_id'), table_name='trend_evidence')
    op.drop_index(op.f('ix_trend_evidence_id'), table_name='trend_evidence')
    op.drop_index('idx_trend_relevance', table_name='trend_evidence')
    op.drop_table('trend_evidence')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_trend_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_event_date'), table_name='calendar_events')
    op.drop_index('idx_user_date', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trends_status'), table_name='trends')
    op.drop_index(op.f('ix_trends_slug'), table_name='trends')
    op.drop_index(op.f('ix_trends_seer_score'), table_name='trends')
    op.drop_index(op.f('ix_trends_name'), table_name='trends')
    op.drop_index(op.f('ix_trends_id'), table_name='trends')
    op.drop_index(op.f('ix_trends_category'), table_name='trends')
    op.drop_index('idx_status_updated', table_name='trends')
    op.drop_index('idx_category_seer_score', table_name='trends')
    op.drop_table('trends')
    op.drop_index(op.f('ix_raw_signals_platform'), table_name='raw_signals')
    op.drop_index(op.f('ix_raw_signals_id'), table_name='raw_signals')
    op.drop_index(op.f('ix_raw_signals_content_created_at'), table_name='raw_signals')
    op.drop_index(op.f('ix_raw_signals_collected_at'), table_name='raw_signals')
    op.drop_index(op.f('ix_raw_signals_category'), table_name='raw_signals')
    op.drop_index('idx_platform_category_created', table_name='raw_signals')
    op.drop_index('idx_category_collected', table_name='raw_signals')
    op.drop_table('raw_signals')
    # ### end Alembic commands ###
